apiVersion: v1
kind: Namespace
metadata:
  name: docker-demo
---
kind: Service
apiVersion: v1
metadata:
  namespace: docker-demo
  name: docker-demo-svc
spec:
  selector:
    app: dockerdemo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  namespace: docker-demo
  name: dockerdemo-deploy
  labels:
    app: dockerdemo-deploy
spec:
  selector:
    matchLabels:
      app: dockerdemo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dockerdemo
    spec:
      containers:
      - image: ehazlett/docker-demo
        name: docker-demo-container
        env:
        - name: app
          value: dockerdemo
        ports:
        - containerPort: 8080
#---
#apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
#kind: Deployment
#metadata:
#  namespace: docker-demo
#  name: netshoot-deploy
#  labels:
#    app: netshoot
#spec:
#  selector:
#    matchLabels:
#      app: netshoot
#  strategy:
#    type: Recreate
#  template:
#    metadata:
#      labels:
#        app: netshoot
#    spec:
#      containers:
#      - image: nicolaka/netshoot
#        name: netshoot
#        command: ["ping","localhost"]
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dockerdemo-ingress
  namespace: docker-demo
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: docker-demo-k8s.demo.dckr.org
    http:
      paths:
      - path: /
        backend:
          serviceName: docker-demo-svc
          servicePort: 8080
