apiVersion: v1
kind: Namespace
metadata:
  name: docker-demo
---
kind: Service
apiVersion: v1
metadata:
  namespace: docker-demo
  name: docker-demo-svc
spec:
  selector:
    app: dockerdemo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: docker-demo
  name: dockerdemo-deploy
  labels:
    app: dockerdemo-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerdemo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dockerdemo
    spec:
      containers:
      - image: mbentley/docker-demo:visual
        name: docker-demo-container
        env:
        - name: app
          value: dockerdemo
        ports:
        - containerPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: docker-demo
  name: dockerdemo-ingress
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: docker-demo.k0s.demo.dckr.org
    http:
      paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: docker-demo-svc
              port:
                number: 8080
